//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEC.ENTITI
{
    using System;
    using System.Collections.Generic;
    
    public partial class NivelesUsuarios
    {
        public int IdNivelUsuario { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IdTecnologia { get; set; }
        public Nullable<int> IdNivel { get; set; }
    
        public virtual Niveles Niveles { get; set; }
        public virtual Tecnologias Tecnologias { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
