//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEC.ENTITI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pruebas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pruebas()
        {
            this.DetallePrueba = new HashSet<DetallePrueba>();
        }
    
        public int IdPrueba { get; set; }
        public int Usuario { get; set; }
        public int IdTecnologia { get; set; }
        public int Nivel { get; set; }
        public System.DateTime FechaIni { get; set; }
        public System.DateTime FechaTer { get; set; }
        public double Calificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePrueba> DetallePrueba { get; set; }
        public virtual Niveles Niveles { get; set; }
        public virtual Tecnologias Tecnologias { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
